### ISSUE TITLE
good start, please provide more details and extend ideas

### ISSUE THREAD

**Issue by hackers-test** [alicersk/seedcount#1]
### Goal
- Who do you imagine will benefit from using this program? 
- How often does one need to analyze this type of data? In other words, does this program automate something that is done frequently, or is something done infrequently enough that users would probably rather just follow a script that they could customize?
- Is there a standardized format for how people record plant frequencies in quadrats, or will users need to re-format their data for this program? 

### Code
- What is PLS?
- How/why is randomness useful for your intended goals?

### Data
- Will the input data be plant observations or seeds, or are these alternative options?
- Are the two alternative options related?

### Ideas
Currently I think you are stuck in the "load data and visualize it" concept, which on its own is not a super useful type of program. So I'd like to continue exploring more ideas to see if we can make the program a bit more novel. 

- Let's focus first on your first type of data in CSV format. Describe it with an example like below. If it is different than this, then please update it.
```
Quadrat    species    frequency
1    A    0.5    
1    C    0.2
1    B    0.1
1    D    0.2
2    A    0.5
2    B    0.4
2    D    0.1
...
```

- Then let's focus on what the question is: How are species distributed among quadrats?

It seems that there are tons and tons of statistics and methods in ecology for trying to answer this type of question. For example, you could look at the `vegan` library in R which has many statistical calculations for community similarity/dissimilarity, etc.. Perhaps you could try to reproduce functions to calculate some of these statistics in Python? In this way your program would provide a useful port of these R package functions to Python. So, you could maybe find one or two statistics that you are most interested in and implement them.

- Next ask, how will a user interact with my program?

A user could enter there CSV data to you in a command-line interface and your program returns the statistic. Easy
```
# input
myprogram --input data.csv
```
```
# output
community dissimiliarity: 0.5
```

So that's step 1. I think you could do it. If that is working then you can begin to ask what you can do next to extend the program? One idea is to create generative data for testing. Imagine the scenario by which communities assemble in this way. Perhaps this can relate back to your idea about seed frequencies. Is there a model to describe how seed dispersal, etc. leads to assembly of communities? You can try to implement this to produce CSV data under a generative process. Then you can calcualte statistics again and see if your metric captures the expected result given the process. 

```
# create a generative function to produce csv data for analysis
myprogram --generate ... 
```

**Comment by alicersk** [comment]
This is helpful feedback. I will also update to make it a little more clear what I want to visualize and why; there are a lot of tools for handling the field data, but what I actually want to do is make a tool  for seed mix design. I've attached a photo of a sketch I did of the process, so now I need to think more about which part of the process I want to program.  I've updated the main page with an idea of how it would work to focus on the design piece more, rather than the post-occupancy analysis (that's where the frequency and quadrats come in) piece. 
![IMG_5278](https://user-images.githubusercontent.com/77415187/108911927-e9824c80-75f5-11eb-911b-1d16ff30c302.jpg)
